title: Venkatachalam K # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am now pursuing master's in business analytics at the University of Utah's David Eccles School of Business, with a major in business intelligence and data analytics.
  <br>I am also working as a data analyst (intern) in Intermountain health, SLC.I enjoy analyzing data with Python, SQL ,R and uses PowerBI, Tableau and Domo to create meaningful business insights and visualizations with multi level granularity. 
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/only2venkat">View My LinkedIn Profile</a> 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
